#    Q.1 Difference between Python version 2 and version 3 ? How do you check current version of python?

Ans:- 

A. Print Function:  Python 2 - print statement is used to print values to the console without using parentheses.
                    Python 3 - print statement has been replaced by the print() function,which requires parentheses.

B. Integer Division:Python 2 - Dividing two integers results in integer division (truncation of the decimal part).
                    Python 3 - Division of integers results in a float, and if you want integer division, you can use                                      the // operator.
                    
C. Unicode Support: Python 2 - Treats strings as sequences of bytes by default, and Unicode support is added using a"u"                                    prefix.
                    Python 3 - Supports Unicode natively, and strings are Unicode by default.

D. Input Function:  Python 2 - the input() function evaluates user input as a Python expression, and raw_input() is used to                                get a string from the user.
                    Python 3 - input() is used to get a string, and eval() is used to evaluate expressions.


Sr No.           Description                       Python 2                          Python 3

  A             Print Function                print "Hello, World!"           print ("Hello, World!")
  
  B            Integer Division                   a = 5 / 2                     a = 5 / 2 |  a = 5 // 2
  
  C            Unicode Support              string = u"Hello, World!"         string = "Hello, World!"
  
  D            Input Function                    name =                        name = input("Enter your name: ")
                                         raw_input("Enter your name: ")
 

In [1]:
#check current version of python?

from platform import python_version
python_version()

'3.11.5'

#    Q.2 Difference between local variable vs global variable ?examples ?

Ans-

1. Local variables - declared inside a function and can only be accessed within that function.
2. Global variable - declared outside a function and can accessed from anywhere in program.

In [2]:
# local variable Example

def Local_variable():
     
    x = 5

print("Output : ", x)

NameError: name 'x' is not defined

In [3]:
# global variable Example

y = 10

def Global_variable():
    print(y)

# Q.3 What are the data types in python ?

Ans - 

There Are Following data types in Python:
Float, Int, String, Boolean 

(a). Integer  = All positive and negative values .
                Example  = a = 67,89,-12,-57,890

(b). FLOAT    = All decimal values .
                Examples = a = 67.89 , 34.567

(c). STRING   = ''(Single Quotes) , " "(Double Quotes) , ''' ''' (Triple Quotes)
                Example  = a = "sam" , 'sam' , '''sam'''

(d). Boolean  = Conditions 
                Correct ==> TRUE , OTHERWISE ==> FALSE


# Q.4 What is difference between Mutable and Immutable Data types ? How many data types are mutable or not ?Please provide reason with examples?

Ans - 

Mutable Data Types - that can be changed after they are created

Immutable Data Types - cannot be changed after they are created.

In [4]:
list = [1, 2, 3]        #Mutable Data Types
list[0] = 4
print(list)

[4, 2, 3]


In [5]:
my_string = "hello"     #Immutable Data Types
my_string[0] = "b"
print(my_string)

TypeError: 'str' object does not support item assignment

# Q.5 Why we use loops ? Please provide 3 examples of for loop and 3 examples of while loop ?
Ans - 
Loops are used in programming to execute a set of statements repeatedly until a certain condition is met.

# FOR LOOP EXAMPLE

In [6]:
for i in range(5):                      # 1st Example
    print(i, end ='')


01234

In [7]:
fruits = ['apple', 'banana', 'orange']   # 2nd Example
for fruit in fruits:
    print(fruit)

apple
banana
orange


In [8]:
a = "sam"                                # 3rd Example
for i in a : 
    print(i, end ='')

sam


# WHILE LOOP EXAMPLE

In [9]:
i = 1
n = 4
while (i<=n):
    print(i, end = '')
    i = i+1

1234

In [10]:
i = 4
n = 1
while (i>=n):
    print(i, end = '')
    i = i-1

4321

In [12]:
i = 1
n = int(input("Enter value :"))
Sum = 0
while(i<=n):
    Sum = Sum + (i*i)
    i = i + 1
print(Sum)

Enter value :5
55


# Q.6 Why we use functions ? Difference between lambda , filter , reduce , map function with examples ? 

Functions are integral parts of every programming language because they help to make code more modular & reusable.

# LAMBDA FUNCTION :

In [14]:
x = lambda a : a+5
print("Final Output is ", x(2))
    

Final Output is  7


# FILTER FUNCTION :

In [ ]:
height = [5,12,20,23,27,89,34,56,78,90]   # container 

def myFunc(x):    
    if(x<=18):
        return True 
    else : 
        return False 
    
kids = list(filter(myFunc , ages)) 
print(kids)

# REDUCE FUNCTION :

In [22]:
from functools import reduce

def multiply(x, y):
    return x * y

numbers = [1, 2, 3, 4, 5]

result = reduce(multiply, numbers)

print(result)

120


# MAP FUNCTION :

In [ ]:
a = [3, '45', False]
b = list(map(int , a))
b

# Q.7 Difference between list and tuple? Please provide index() , insert() , append(), reverse() , pop() explain with examples ?

Difference Between LIST & TUPLE : 

The literal syntax of tuples is shown by parentheses () whereas the literal syntax of lists is shown by square brackets []

# .index() :
This function is used to find the index of the object

In [25]:
a = ['sam'  , 90 , 45.89 , 'kriti']
a.index('kriti')

3

# .insert() :

This function is used to insert an object at the given indexing.

In [34]:
a = ['sam' , 90 , 'rahul' , 'kriti']
print(a)
a.insert(1 , "rahul") 
print(a) 

['sam', 90, 'rahul', 'kriti']
['sam', 'rahul', 90, 'rahul', 'kriti']


# .append() :

This function is used to add an element in the last indexing of container .

In [35]:
a = ['sam' , 98 , 'mohit' , 78.43] 
print(a) 
a.append("preeti")
print(a) 

['sam', 98, 'mohit', 78.43]
['sam', 98, 'mohit', 78.43, 'preeti']


# .reverse() :

This function is used to reverse an element present in the list

In [50]:
a = ['sam' , 90 , 'rahul' , 'kriti']
print(a) 
a.reverse() 
print(a) 

['sam', 90, 'rahul', 'kriti']
['kriti', 'rahul', 90, 'sam']


# .pop() :
    
This function is used to delete the last element from the list

In [12]:
a = ['sam' , 90 , 'rahul' , 'kriti']
print(a)
a.pop() 
print(a)
a.pop() 
print(a)

['sam', 90, 'rahul', 'kriti']
['sam', 90, 'rahul']
['sam', 90]


# Q.8 Difference between dictionary vs set? Please provide keys() , values() ,items() example of dictionary and union() , intersection() in sets ? Is FrozenSet is mutable or not ? 
Ans - 

Sets store unique elements, while dictionaries store related pieces of information. 
Sets are an unordered collection of unique elements, whereas a dictionary is an ordered collection of key-value pairs

# .Union() :

In [3]:
a = {'sam' , 'rahul' , 'pooja'}   #Key Output using Union in Set
b = {'karan' , 'pooja'} 
c = a.union(b) 
print(c) 

{'rahul', 'sam', 'karan', 'pooja'}


In [6]:
a = {1, 2, 3, 4, 5}               #values Output using Union in Set
b = {3, 4, 5, 6, 7}
c = a.union(b) 
print(c) 

{1, 2, 3, 4, 5, 6, 7}


In [8]:
a = {1, 'sam' , 2, 3, 4, 5, 'rahul' , 'pooja'}    #items Output using Union in Set
b = {3, 4, 'karan' , 'pooja', 5, 6, 7,}
c = a.union(b) 
print(c) 

{1, 2, 3, 4, 5, 6, 7, 'sam', 'karan', 'pooja', 'rahul'}


# .intersection() :

In [5]:
a = {'sam' , 'rahul' , 'pooja'}            #Key Output using intersection in Set
b = {'karan' , 'pooja', 'rahul'} 
c = a.intersection(b) 
print(c) 

{'rahul', 'pooja'}


In [7]:
a = {1, 2, 3, 4, 5}                       #values Output using intersection in Set
b = {3, 4, 5, 6, 7}
c = a.intersection(b) 
print(c) 

{3, 4, 5}


In [10]:
a = {1, 'sam' , 2, 3, 4, 5, 'rahul' , 'pooja'}    #items Output using intersection in Set
b = {3, 4, 'rahul' , 'pooja', 5, 6, 7,}
c = a.intersection(b) 
print(c) 

{3, 4, 5, 'pooja', 'rahul'}


# Is FrozenSet is mutable or not ?
No, frozenset in Python is immutable. Once a frozenset is created, you cannot modify its elements by adding or removing elements. 

# Q.9 What are decorators? 

A decorator in Python is a function that takes another function as input and returns a new function that usually extends or modifies the behavior of the original function.

# Q.10 What is list comprehension? Please provide example ?
Ans -

 It allows you to create a new list by applying an expression to each item in an existing iterable (e.g., a list, tuple, or range) and optionally filtering the items based on a condition.

In [163]:
squares = [x**2 for x in range(5)]
squares

[0, 1, 4, 9, 16]

# Q.11 How do you create an array from a user defined list ?

In [150]:
import numpy as np

user_defined_list = [1, 2, 3, 4, 5]
print(type(user_defined_list))

np.array(user)

<class 'list'>


array([1, 2, 3, 4, 5])

# Q.12 Difference between hstack() vs vstack() with example ?

# hstack() :

This function is used to stack arrays in a horizontal sequence

In [138]:
array_1 = np.array([1, 2, 3])
array_2 = np.array([4, 5, 6])

print(array_1)
print(array_2)

hstack = np.hstack((array_1, array_2)) # Horizontal stack
hstack

[1 2 3]
[4 5 6]


array([1, 2, 3, 4, 5, 6])

# vstack() :

This function is used to stack arrays in a vertical sequence

In [137]:
array_1 = np.array([1, 2, 3])
array_2 = np.array([4, 5, 6])

print(array_1)
print(array_2)

hstack = np.vstack((array_1, array_2)) # Horizontal stack
hstack

[1 2 3]
[4 5 6]


array([[1, 2, 3],
       [4, 5, 6]])

# Q.13  What is Broadcasting in NumPy ? Please provide an example ? 

ANS- 

Broadcasting is a powerful feature that simplifies the syntax for performing operations on arrays with different shapes, making code more concise and readable.

In [132]:
import numpy as np

a = np.array([1, 2, 3])

scalar = 2


result = a * scalar

print("Before Broadcsting Array:", a)

print("\nResult after Broadcasting:", result)


Before Broadcsting Array: [1 2 3]

Result after Broadcasting: [2 4 6]


# Q.14 What is zeros() , ones() , eye() , diag() , randint() , rand() , seed(), linspace() , unique() in NumPy ? please provide explanation with example ? 

# .zeros() : 
This function creates an array and fill all the values with zeros .

In [94]:
import numpy as np 
a = np.zeros((3,3))
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

# .ones() : 
This function creates an array and fill all the values with ones .

In [77]:
import numpy as np 
a = np.ones((3,3))
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

# .eye() : 

This function creates an array with all the digonal elements as 1 and rest are 0.

In [87]:
import numpy as np 
a = np.eye(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# .diag() 

This function creates an array in which we can pass our custom array at the digonal position . and rest all are the zeros .

In [85]:
import numpy as np 

a = np.array([1,56,78,90])
a
b = np.diag(b)
b

array([ 1, 56, 78, 90])

# .Randint() 

This function is used to generate a random number between a given range .

In [91]:
a = np.random.randint(1,10,3)
a

array([4, 2, 7])

# . Rand() 

This function is used to generate a random number between 0 to 1

In [92]:
a = np.random.rand(5)
a

array([0.27908709, 0.21498076, 0.72477103, 0.32535976, 0.59767915])

# Seed Function()

It fix our random data .  

In [95]:
np.random.seed(2) 
a = np.random.randint(1,10,3)
a

array([9, 9, 7])

# LinSpace()

This function returns value between a given range and with a same gap between consicutive elements .

In [96]:
a = np.linspace(1,2,5)   
a

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

# .unique() :

returns 3 array .

A. The array with unique values .
B. The array with respective index values .
C. The array witth counting of frequency .

In [107]:
a = np.array([10,20,10,30,10,40,20,50,20,60]) 
print(a)

np.unique(a , return_index = True , return_counts = True)

[10 20 10 30 10 40 20 50 20 60]


(array([10, 20, 30, 40, 50, 60]),
 array([0, 1, 3, 5, 7, 9], dtype=int64),
 array([3, 3, 1, 1, 1, 1], dtype=int64))

# Q.15 How can you reshape your array in NumPy? What is argmin() and argmax() in NumPy ? Please explain with example ?

In [115]:
a = np.random.randint(1,50,12)
a

array([13,  5, 27, 16, 40, 47,  9, 46, 16, 42, 46,  9])

In [116]:
a.reshape(2,6)

array([[13,  5, 27, 16, 40, 47],
       [ 9, 46, 16, 42, 46,  9]])

# .argmax():

 is used to find the indices of the maximum values along a specified axis of an array.

In [125]:
import numpy as np
b = np.array([3, 1, 4, 1, 5, 9, 2, 6])
b

array([3, 1, 4, 1, 5, 9, 2, 6])

In [123]:
np.argmax(b)

3

# .argmin():

 is used to find the indices of the minimum values along a specified axis of an array.

In [126]:
np.argmin(b)

1